CanalTP/tartare

Procfile
requirements.txt
tartare/__init__.py
tartare/default_settings.py
tartare/helper.py
tartare/tasks.py

For the moment it only watch a directory and move all the files to another directory.

init of the project

---

README.md
requirements_dev.txt
tartare/default_settings.py
tartare/tasks.py
tests/update_data_test.py

- added a test for tartare.tasks.update_data_task
- added documentation

add simple test move data

---

Dockerfile
tartare/__init__.py

we don't want to use flask server in production, we use uwsgi

use uwsgi for production

---

tartare/default_settings.py

else we'll get others message (like navitia's)

bind custom queue to custom exchange

---

tartare/core/calendar_handler.py
tartare/default_settings.py
tartare/interfaces/grid_calendar.py
tartare/tasks.py
tests/integration/rest_api_test.py
tests/integration/update_data_test.py

Handle ntfs or calendar file
Merge if necessary

Do merge ntfs & calendar

---

Dockerfile

reduced size of docker image

---

requirements.txt
tartare/__init__.py
tartare/api.py
tartare/core/models.py
tartare/default_settings.py
tartare/interfaces/coverages.py
tartare/interfaces/schema.py

store coverages in mongo db and add a get and a post API around it.
TODO:
Questions:
@kinnou02 can you take a look at this ?

first draft around coverages handling

---

requirements_dev.txt
tests/__init__.py
tests/conftest.py
tests/docker_wrapper.py

start a mongo docker for tests

---

tests/integration/__init__.py
tests/integration/conftest.py
tests/integration/mongo/__init__.py
tests/integration/mongo/conftest.py
tests/integration/mongo/coverage_api_test.py
tests/integration/rest_api_test.py
tests/utils.py

now all tests that need a mongo db needs to be in integration/mongo

small refacto: move some tests file

---

tartare/core/__init__.py
tartare/core/models.py
tartare/default_settings.py
tartare/interfaces/coverages.py
tartare/interfaces/schema.py
tartare/tasks.py
tests/integration/mongo/coverage_api_test.py

I'll wait for #32 to be merged not to have conflicts
there is still the /calendar api that needs to be ported.
(and I don't like the way the Coverage is {de}serialized, we need to find a way to better do this)

use coverages in tartare

---

tartare/interfaces/index.py
tests/integration/mongo/rest_api_test.py

It's always nice to have a 200 when you call the root of an application :)
I added links to main resources following the HAL specification, it's
always useful.

Add a resource on /

---

requirements.txt
requirements_dev.txt
tartare/helper.py
tests/helper_test.py

first step for upload to tyr :)

add a function for uploading big file in http

---

tartare/api.py
tartare/core/data_handler.py
tartare/interfaces/data_update.py
tartare/tasks.py
tests/integration/mongo/conftest.py
tests/integration/mongo/contributors_api_test.py
tests/integration/mongo/coverage_api_test.py
tests/integration/mongo/coverage_data_update_api_test.py
tests/integration/mongo/rest_api_test.py
tests/utils.py

Should be safer to merge https://github.com/CanalTP/tartare/pull/49 and then rebase this PR.

change /geo_data to /data_update with refacto

---

Dockerfile
README.md
docker-compose.yml
tartare/core/models.py
tartare/default_settings.py
tartare/interfaces/schema.py
tartare/tasks.py
tests/integration/mongo/conftest.py
tests/integration/mongo/coverage_api_test.py
tests/integration/mongo/grid_calendars_test.py
tests/integration/mongo/models_test.py
tests/integration/mongo/update_data_test.py

input, current and output no longer needed as we POST
TODO:

Cleanup work directories

---

tartare/api.py
tartare/core/models.py
tartare/helper.py
tartare/interfaces/contributors.py
tartare/interfaces/data_sets.py
tartare/interfaces/data_sources.py
tartare/interfaces/index.py
tartare/interfaces/schema.py
tests/helper_test.py
tests/integration/mongo/data_sources_api_test.py

contributors interface POST and PATCH methods have been completed to enable a nice data_source manipulation.
Feel free to discuss :)

DataSources in /contributors API

---

documentation/openAPI.yaml

Fixing issue https://github.com/CanalTP/tartare/issues/68
The api behavior have been tested.

Doc: fix openAPI

---

tartare/core/models.py

Once this cleaning has passed on DEV, INt and CUSTO, we can merge that PR because that cleaning won't be necessary anymore
TODO:

Remove technical_conf cleaning

---

README.md
tartare/core/models.py
tartare/interfaces/contributors.py
tartare/interfaces/data_sets.py
tartare/interfaces/data_sources.py
tests/integration/mongo/contributors_api_test.py
tests/integration/mongo/data_sources_api_test.py
tests/utils.py

data_sources CRUD

---

documentation/openAPI.yaml
tartare/core/models.py
tartare/exceptions.py
tartare/interfaces/contributors.py
tartare/interfaces/coverage_data_source_subscription.py
tartare/interfaces/coverages.py
tartare/interfaces/data_sets.py
tartare/interfaces/data_sources.py
tartare/interfaces/data_update.py
tartare/interfaces/grid_calendar.py
tests/integration/mongo/contributors_api_test.py
tests/integration/mongo/coverage_data_source_subscription_test.py
tests/integration/mongo/coverage_data_update_api_test.py
tests/integration/mongo/grid_calendars_test.py
tests/integration/mongo/update_data_test.py

raise custom http exceptions (400, 404, 409 and 500) that are rendered to
```json
{
"message": "Invalid arguments",
"error": "detailed message"
}
```

added custom exceptions

---

documentation/stif_plan.md

doc: draft plan for STIF management

---

documentation/openAPI.yaml
tartare/core/models.py
tartare/interfaces/data_sources.py
tests/integration/mongo/conftest.py
tests/integration/mongo/contributors_api_test.py
tests/integration/mongo/data_sources_api_test.py

```json
{
"id": "tram_lyon",
"name": "Tram feed for Lyon",
"data_format": "gtfs",
"input": [
{
"type": "url",
"url": "http://stif.com/od.zip"
}
]
}
```

added input to data source

---

tartare/core/context.py
tartare/core/contributor_export_functions.py
tartare/dataset_fetcher.py
tartare/interfaces/contributor_export.py
tartare/tasks.py
tartare/url_dataset_fetcher.py
tests/integration/dataset_fetcher_test.py

```
curl -i -X POST \
-H "Content-Type:application/json" \
-d \
'{
"id": "contrib-israel-multi",
"name": "ISR",
"data_prefix": "ISR_MULTI_",
"data_sources": [
{
"name": "myHTTPDS",
"input": {
"type": "url",
"url": "https://navitia.opendatasoft.com/explore/dataset/il/files/400d7da94eaacb5e52c612f8ac28e420/download/"
}
},
{
"name": "myFTPDS",
"input": {
"type": "ftp",
"url": "ftp://gtfs.mot.gov.il/israel-public-transportation.zip"
}
}
]
}' \
'http://tartare-ws.local.canaltp.fr:5000/contributors'
```
then do an export with
```
curl -i -X POST \
-H "Content-Type:application/json" \
-d \
'' \
'http://tartare-ws.local.canaltp.fr:5000/contributors/contrib-israel-multi/actions/export'
```

Manage dataset import for contributor

---

tartare/interfaces/contributors.py
tests/integration/mongo/contributors_api_test.py

The following request should not return 500 error, 201 instead: 
```
curl -i -X POST \
-H "Content-Type:application/json" \
-d \
'{
"name": "BUG",
"data_prefix": "BUG_"
}' \
'http://tartare-ws.local.canaltp.fr:5000/contributors'
```
and test __test_add_contributor_without_id__ should pass

fix internal error and add test
